# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- testbranch

#pool:
#  vmImage: 'ubuntu-latest'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'
- stage: tests
  displayName: tests
  jobs:
  - job: tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: "JaCoCo"
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
          reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
          failIfCoverageEmpty: true
